import type { Db } from "mongodb";
import {
  COLLECTIONS,
  type EventDoc,
  type ExpenseDoc,
  type MemberDoc,
  type MessageDoc,
  type PhotoDoc,
  type TicketDoc,
  type TripDoc,
} from "@tripsync/schema";

export const BOSTON_CREW_TRIP_ID = "trip_tokyo_2026_05";
export const BOSTON_CREW_GROUP_ID = "grp_boston_crew";

const ISO_NOW = "2026-05-11T00:00:00-04:00";

const TRIP: TripDoc = {
  _id: BOSTON_CREW_TRIP_ID,
  group_id: BOSTON_CREW_GROUP_ID,
  title: "Tokyo 5/26-5/30",
  destination: "Tokyo, Japan",
  start_date: "2026-05-26",
  end_date: "2026-05-30",
  status: "planning",
  budget_krw_per_night: 150000,
  decisions: { hotel: null, flight: null, activities: [] },
  created_at: ISO_NOW,
  updated_at: ISO_NOW,
};

const MEMBERS: MemberDoc[] = [
  {
    _id: "mem_seo",
    trip_id: BOSTON_CREW_TRIP_ID,
    user_handle: "seo",
    display_name: "Seo",
    avatar_color: "#E07856",
    role: "owner",
  },
  {
    _id: "mem_jamie",
    trip_id: BOSTON_CREW_TRIP_ID,
    user_handle: "jamie",
    display_name: "Jamie",
    avatar_color: "#3B7A57",
    role: "member",
  },
  {
    _id: "mem_min",
    trip_id: BOSTON_CREW_TRIP_ID,
    user_handle: "min",
    display_name: "Min",
    avatar_color: "#7E5A9B",
    role: "member",
  },
];

const MESSAGES: MessageDoc[] = [
  {
    _id: "msg_001",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "seo",
    body: "Tokyo is locked for May 26-30. Let’s keep this trip calm, visual, and easy to film.",
    created_at: "2026-05-10T20:00:00-04:00",
  },
  {
    _id: "msg_002",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "jamie",
    body: "I’m in. I care most about staying near transit and avoiding the most crowded blocks.",
    created_at: "2026-05-10T20:02:00-04:00",
  },
  {
    _id: "msg_003",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "min",
    body: "Count me in. I uploaded the flight, hotel, and teamLab tickets so the agent can organize them.",
    created_at: "2026-05-10T20:03:00-04:00",
  },
  {
    _id: "msg_004",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "agent",
    body: "Trip state loaded\n1. Dates: May 26-30, 2026\n2. Members: Seo, Jamie, Min\n3. Stored artifacts: itinerary, ticket QR data, expenses, and photos",
    created_at: "2026-05-10T20:04:00-04:00",
  },
  {
    _id: "msg_005",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "seo",
    body: "Use our past high-rated memories to suggest a quiet Tokyo route that will look good in the recap video.",
    created_at: "2026-05-10T20:07:00-04:00",
  },
  {
    _id: "msg_006",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "agent",
    body: "Recommended route\n1. Yoyogi Park in the morning for soft light and space\n2. Daikanyama cafes for stylish B-roll\n3. Shinjuku Gyoen for a calm picnic scene\n4. Nakameguro at golden hour for the closing walk",
    created_at: "2026-05-10T20:08:00-04:00",
  },
  {
    _id: "msg_007",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "jamie",
    body: "Can the trip tools show what happens after uploads? I want the demo to prove tickets, QR, plans, and split are not just chat text.",
    created_at: "2026-05-10T20:10:00-04:00",
  },
  {
    _id: "msg_008",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "agent",
    body: "Trip tools updated\n1. Next plan: Haneda arrival, Shibuya check-in, teamLab entry, Daikanyama walk\n2. Ticket QR: Korean Air, hotel, and teamLab records parsed\n3. Split: three shared expenses summarized with who-pays-whom transfers\n4. Photos: seven recap-ready images synced",
    created_at: "2026-05-10T20:11:00-04:00",
  },
  {
    _id: "msg_009",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "min",
    body: "Open Ticket QR during the demo and show that the agent extracted the confirmation data, not just a title.",
    created_at: "2026-05-10T20:13:00-04:00",
  },
  {
    _id: "msg_010",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "agent",
    body: "Ticket QR ready\n1. Korean Air flight: KE2105, GMP to HND, seat 12A\n2. Shibuya hotel: confirmation SSE-88472193\n3. teamLab entry: order TLB-44109 for 3 guests\nOpen the Ticket QR card to inspect the parsed records.",
    created_at: "2026-05-10T20:14:00-04:00",
  },
  {
    _id: "msg_011",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "seo",
    body: "Now show the money side. The judges should see who paid, what was split, and the final transfer.",
    created_at: "2026-05-10T20:16:00-04:00",
  },
  {
    _id: "msg_012",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "agent",
    body: "Split summary\n1. Jamie paid the Shibuya hotel deposit\n2. Seo paid the Ebisu dinner\n3. Min paid the shared Suica top-up\n4. Settlement: Min pays Jamie, and Seo pays Jamie\nOpen Split to inspect every expense and transfer.",
    created_at: "2026-05-10T20:17:00-04:00",
  },
  {
    _id: "msg_013",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "jamie",
    body: "The recap should use real trip photos. Show that the Photos card has places and captions before we render.",
    created_at: "2026-05-10T20:19:00-04:00",
  },
  {
    _id: "msg_014",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "agent",
    body: "Photo set ready\n1. Haneda arrival board\n2. Shibuya crossing\n3. Three Azabudai Hills/teamLab angles\n4. Daikanyama cafe street\n5. Nakameguro river at golden hour\nOpen Photos to choose which moments belong in the recap.",
    created_at: "2026-05-10T20:20:00-04:00",
  },
  {
    _id: "msg_015",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "min",
    body: "Before rendering, I want to choose what goes into the 60-second video instead of blindly generating it.",
    created_at: "2026-05-10T20:22:00-04:00",
  },
  {
    _id: "msg_016",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "agent",
    body: "Video studio ready\n1. Include or exclude scenes\n2. Include or exclude photos\n3. Add plan, ticket, and settlement beats\n4. Render a 60-second vertical video with audio in the Video tab",
    created_at: "2026-05-10T20:23:00-04:00",
  },
  {
    _id: "msg_017",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "seo",
    body: "Render the version with Haneda, Shibuya, the ticket QR beat, the split summary, and the best golden-hour photos.",
    created_at: "2026-05-10T20:25:00-04:00",
  },
  {
    _id: "msg_018",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "agent",
    body: "Playable recap created\n1. Format: vertical 9:16\n2. Duration: 60 seconds\n3. Source: selected trip tools and synced photos\n4. Output: ready in the Video tab",
    created_at: "2026-05-10T20:26:00-04:00",
  },
];

const EVENTS: EventDoc[] = [
  {
    _id: "event_hnd_arrival",
    trip_id: BOSTON_CREW_TRIP_ID,
    title: "Arrive at Haneda",
    starts_at: "2026-05-26T10:35:00+09:00",
    ends_at: null,
    location: "Haneda Airport Terminal 3",
    source: "ticket",
    source_id: "ticket_flight_hnd",
    status: "open",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "event_hotel_checkin",
    trip_id: BOSTON_CREW_TRIP_ID,
    title: "Check in near Shibuya",
    starts_at: "2026-05-26T15:00:00+09:00",
    ends_at: null,
    location: "Shibuya Stream Excel Hotel Tokyu",
    source: "ticket",
    source_id: "ticket_hotel_shibuya",
    status: "open",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "event_teamlab_entry",
    trip_id: BOSTON_CREW_TRIP_ID,
    title: "teamLab Borderless entry",
    starts_at: "2026-05-27T11:00:00+09:00",
    ends_at: "2026-05-27T13:00:00+09:00",
    location: "Azabudai Hills",
    source: "ticket",
    source_id: "ticket_teamlab",
    status: "open",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "event_daikanyama_walk",
    trip_id: BOSTON_CREW_TRIP_ID,
    title: "Daikanyama golden-hour walk",
    starts_at: "2026-05-28T17:30:00+09:00",
    ends_at: "2026-05-28T19:00:00+09:00",
    location: "Daikanyama, Tokyo",
    source: "seed",
    source_id: "seed_daikanyama_walk",
    status: "open",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
];

const TICKETS: TicketDoc[] = [
  {
    _id: "ticket_flight_hnd",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "seo",
    type: "flight",
    vendor: "Korean Air",
    amount: 386000,
    currency: "KRW",
    details_json: {
      flight_number: "KE2105",
      from: "GMP",
      to: "HND",
      seat: "12A",
      confirmation: "TOKYO26",
    },
    pdf_url: "https://example.com/demo/tokyo-flight.pdf",
    qr_data: "M1KIM/SEO TOKYO26 GMPHNDKE2105 026Y012A0001",
    status: "parsed",
    starts_at: "2026-05-26T08:20:00+09:00",
    ends_at: "2026-05-26T10:35:00+09:00",
    latitude: 35.5494,
    longitude: 139.7798,
    origin_latitude: 37.5583,
    origin_longitude: 126.7906,
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "ticket_hotel_shibuya",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "jamie",
    type: "hotel",
    vendor: "Shibuya Stream Excel Hotel Tokyu",
    amount: 592000,
    currency: "KRW",
    details_json: {
      check_in: "2026-05-26T15:00:00+09:00",
      check_out: "2026-05-30T11:00:00+09:00",
      guests: 3,
      room: "Twin + sofa bed",
      confirmation: "SSE-88472193",
    },
    pdf_url: "https://example.com/demo/shibuya-hotel.pdf",
    qr_data: "https://hotel.example/booking/SSE-88472193",
    status: "parsed",
    starts_at: "2026-05-26T15:00:00+09:00",
    ends_at: "2026-05-30T11:00:00+09:00",
    latitude: 35.6576,
    longitude: 139.7024,
    origin_latitude: null,
    origin_longitude: null,
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "ticket_teamlab",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "min",
    type: "event",
    vendor: "teamLab Borderless",
    amount: 126000,
    currency: "KRW",
    details_json: {
      date: "2026-05-27",
      time: "11:00",
      tickets: 3,
      confirmation: "TLB-44109",
    },
    pdf_url: "https://example.com/demo/teamlab-borderless.pdf",
    qr_data: "https://teamlab.art/eticket/TLB-44109?party=3",
    status: "parsed",
    starts_at: "2026-05-27T11:00:00+09:00",
    ends_at: "2026-05-27T13:00:00+09:00",
    latitude: 35.6602,
    longitude: 139.7407,
    origin_latitude: null,
    origin_longitude: null,
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
];

const EXPENSES: ExpenseDoc[] = [
  {
    _id: "expense_hotel_deposit",
    trip_id: BOSTON_CREW_TRIP_ID,
    payer: "jamie",
    amount: 592000,
    currency: "KRW",
    description: "Shibuya hotel deposit",
    split_among: ["seo", "jamie", "min"],
    source: "receipt",
    receipt_url: "https://example.com/demo/shibuya-hotel-receipt.jpg",
    status: "parsed",
    created_at: "2026-05-11T00:10:00-04:00",
    updated_at: "2026-05-11T00:10:00-04:00",
  },
  {
    _id: "expense_izakaya_dinner",
    trip_id: BOSTON_CREW_TRIP_ID,
    payer: "seo",
    amount: 138000,
    currency: "KRW",
    description: "Ebisu izakaya dinner",
    split_among: ["seo", "jamie", "min"],
    source: "receipt",
    receipt_url: "https://example.com/demo/ebisu-dinner-receipt.jpg",
    status: "parsed",
    created_at: "2026-05-11T00:12:00-04:00",
    updated_at: "2026-05-11T00:12:00-04:00",
  },
  {
    _id: "expense_suica_topup",
    trip_id: BOSTON_CREW_TRIP_ID,
    payer: "min",
    amount: 45000,
    currency: "KRW",
    description: "Shared Suica top-up",
    split_among: ["seo", "jamie", "min"],
    source: "text",
    receipt_url: null,
    status: "parsed",
    created_at: "2026-05-11T00:14:00-04:00",
    updated_at: "2026-05-11T00:14:00-04:00",
  },
];

const PHOTOS: PhotoDoc[] = [
  {
    _id: "photo_hnd_arrival_seo",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "seo",
    url: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    taken_at: "2026-05-26T10:50:00+09:00",
    latitude: 35.5494,
    longitude: 139.7798,
    width: 1200,
    height: 1600,
    caption: "Haneda arrival board before the city run",
    place_name: "Haneda Airport",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_shibuya_crossing_jamie",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "jamie",
    url: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=1200&q=80",
    taken_at: "2026-05-26T18:12:00+09:00",
    latitude: 35.6595,
    longitude: 139.7005,
    width: 1200,
    height: 800,
    caption: "First evening crossing through Shibuya",
    place_name: "Shibuya Crossing",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_teamlab_seo",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "seo",
    url: "https://images.unsplash.com/photo-1554797589-7241bb691973?w=1200&q=80",
    taken_at: "2026-05-27T11:18:00+09:00",
    latitude: 35.6602,
    longitude: 139.7407,
    width: 1200,
    height: 1600,
    caption: "Lights folding around the room",
    place_name: "Azabudai Hills",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_teamlab_jamie",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "jamie",
    url: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    taken_at: "2026-05-27T11:19:00+09:00",
    latitude: 35.6602,
    longitude: 139.7407,
    width: 1200,
    height: 1600,
    caption: "Jamie catching the mirror room angle",
    place_name: "Azabudai Hills",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_teamlab_min",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "min",
    url: "https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?w=1200&q=80",
    taken_at: "2026-05-27T11:20:00+09:00",
    latitude: 35.6602,
    longitude: 139.7407,
    width: 1200,
    height: 1600,
    caption: "Min under the blue light wall",
    place_name: "Azabudai Hills",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_daikanyama_cafe",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "seo",
    url: "https://images.unsplash.com/photo-1492571350019-22de08371fd3?w=1200&q=80",
    taken_at: "2026-05-28T17:42:00+09:00",
    latitude: 35.6481,
    longitude: 139.7036,
    width: 1200,
    height: 900,
    caption: "Quiet side street before coffee",
    place_name: "Daikanyama",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_nakameguro_river",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "min",
    url: "https://images.unsplash.com/photo-1557409518-691ebcd96038?w=1200&q=80",
    taken_at: "2026-05-28T18:20:00+09:00",
    latitude: 35.6444,
    longitude: 139.6992,
    width: 1200,
    height: 800,
    caption: "Golden hour along the river",
    place_name: "Nakameguro",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
];

export async function seedBostonCrew(db: Db): Promise<void> {
  await db.collection<TripDoc>(COLLECTIONS.trips).insertOne(TRIP);
  await db.collection<MemberDoc>(COLLECTIONS.members).insertMany(MEMBERS);
  await db.collection<MessageDoc>(COLLECTIONS.messages).insertMany(MESSAGES);
  await db.collection<EventDoc>(COLLECTIONS.events).insertMany(EVENTS);
  await db.collection<TicketDoc>(COLLECTIONS.tickets).insertMany(TICKETS);
  await db.collection<ExpenseDoc>(COLLECTIONS.expenses).insertMany(EXPENSES);
  await db.collection<PhotoDoc>(COLLECTIONS.photos).insertMany(PHOTOS);
}

export const bostonCrewFixture = {
  trip: TRIP,
  members: MEMBERS,
  messages: MESSAGES,
  events: EVENTS,
  tickets: TICKETS,
  expenses: EXPENSES,
  photos: PHOTOS,
};
