import path from "node:path";
import type { Db } from "mongodb";
import {
  COLLECTIONS,
  type EventDoc,
  type ExpenseDoc,
  type MediaAssetDoc,
  type MemberDoc,
  type MessageDoc,
  type PhotoDoc,
  type TicketDoc,
  type TripDoc,
} from "@tripsync/schema";

export const BOSTON_CREW_TRIP_ID = "trip_tokyo_2026_05";
export const BOSTON_CREW_GROUP_ID = "grp_boston_crew";

const ISO_NOW = "2026-05-11T00:00:00-04:00";
const API_BASE = "http://localhost:4000";
const DEMO_ASSET_BASE = `${API_BASE}/assets/demo`;
const DEMO_VIDEO_PATH = path.resolve(process.cwd(), "apps/api/assets/demo/videos/uploaded-trip-highlights.mp4");

const TRIP: TripDoc = {
  _id: BOSTON_CREW_TRIP_ID,
  group_id: BOSTON_CREW_GROUP_ID,
  title: "Tokyo 5/26-5/30",
  destination: "Tokyo, Japan",
  start_date: "2026-05-26",
  end_date: "2026-05-30",
  status: "planning",
  budget_krw_per_night: 150000,
  decisions: { hotel: null, flight: null, activities: [] },
  created_at: ISO_NOW,
  updated_at: ISO_NOW,
};

const MEMBERS: MemberDoc[] = [
  {
    _id: "mem_seo",
    trip_id: BOSTON_CREW_TRIP_ID,
    user_handle: "seo",
    display_name: "Seo",
    avatar_color: "#E07856",
    role: "owner",
  },
  {
    _id: "mem_jamie",
    trip_id: BOSTON_CREW_TRIP_ID,
    user_handle: "jamie",
    display_name: "Jamie",
    avatar_color: "#3B7A57",
    role: "member",
  },
  {
    _id: "mem_min",
    trip_id: BOSTON_CREW_TRIP_ID,
    user_handle: "min",
    display_name: "Min",
    avatar_color: "#7E5A9B",
    role: "member",
  },
];

const MESSAGES: MessageDoc[] = [
  {
    _id: "msg_001",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "seo",
    body: "May 26-30 is locked. I want the recap to use the real photos and clips we already saved, not generic city shots.",
    created_at: "2026-05-10T20:00:00-04:00",
  },
  {
    _id: "msg_002",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "jamie",
    body: "I'm in. I added the tennis court warm-up and beach walk photos because those feel the most like us.",
    created_at: "2026-05-10T20:02:00-04:00",
  },
  {
    _id: "msg_003",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "min",
    body: "I forwarded the flight, rental, Getty, and Antelope confirmations. Please keep the QR and order numbers easy to open.",
    created_at: "2026-05-10T20:03:00-04:00",
  },
  {
    _id: "msg_004",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "agent",
    body: "Trip packet saved\n1. Dates: May 26-30, 2026\n2. Members: Seo, Jamie, Min\n3. Ready sections: next plan, ticket QR records, receipts, shared split, photos, video clip, and music",
    created_at: "2026-05-10T20:04:00-04:00",
  },
  {
    _id: "msg_005",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "seo",
    body: "Can you use our high-rated food and beach memories to shape the route? I want the recap to feel personal.",
    created_at: "2026-05-10T20:07:00-04:00",
  },
  {
    _id: "msg_006",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "agent",
    body: "Recommended route\n1. Morning activity beat from the tennis photo\n2. Food table beat from the stew and lobster shots\n3. Quiet walk beat from the beach clip\n4. Golden-hour close with the vertical photos",
    created_at: "2026-05-10T20:08:00-04:00",
  },
  {
    _id: "msg_007",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "jamie",
    body: "After we land, what do we need first? Put the flight, rental pickup, Getty time, and Antelope booking in one place.",
    created_at: "2026-05-10T20:10:00-04:00",
  },
  {
    _id: "msg_008",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "agent",
    body: "Next plan updated\n1. Flight arrival and first transfer\n2. Rental pickup confirmation\n3. Getty entry window\n4. Antelope booking time and QR",
    created_at: "2026-05-10T20:11:00-04:00",
  },
  {
    _id: "msg_009",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "min",
    body: "Can you keep the ticket confirmations handy? I don't want to search PDFs when someone asks for a QR.",
    created_at: "2026-05-10T20:13:00-04:00",
  },
  {
    _id: "msg_010",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "agent",
    body: "Ticket QR records saved\n1. Delta flight PDF with boarding QR text\n2. Hertz rental confirmation L1101312472\n3. Getty order 2525775\n4. Antelope booking 266145927",
    created_at: "2026-05-10T20:14:00-04:00",
  },
  {
    _id: "msg_011",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "seo",
    body: "Jamie paid the big booking, I paid the seafood receipt, and Min added another dinner receipt plus transit. Can you tell us who owes whom?",
    created_at: "2026-05-10T20:16:00-04:00",
  },
  {
    _id: "msg_012",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "agent",
    body: "Split summary\n1. Jamie paid the large booking\n2. Seo paid the seafood receipt\n3. Min paid dinner receipt and transit\n4. Settlement: Min pays Jamie, and Seo pays Jamie",
    created_at: "2026-05-10T20:17:00-04:00",
  },
  {
    _id: "msg_013",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "jamie",
    body: "I added the tennis, beach, stew, lobster, and vertical travel photos. Please group them by moment so the video does not feel random.",
    created_at: "2026-05-10T20:19:00-04:00",
  },
  {
    _id: "msg_014",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "agent",
    body: "Photo set organized\n1. Activity: tennis court\n2. Coast: beach walk\n3. Food: stew, lobster, dinner table\n4. Vertical details: travel stills for transitions\n5. Close: final night frame",
    created_at: "2026-05-10T20:20:00-04:00",
  },
  {
    _id: "msg_015",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "min",
    body: "For the recap, leave out anything boring. Keep the uploaded highlight clip, the best food photos, one QR beat, one receipt beat, and the final split.",
    created_at: "2026-05-10T20:22:00-04:00",
  },
  {
    _id: "msg_016",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "agent",
    body: "Video mix prepared\n1. Uploaded clip is trimmed to the strongest section\n2. Photos can be included or removed\n3. Ticket QR, receipt, and split beats can pop up as bubbles\n4. A random music track is selected for the 60-second vertical render",
    created_at: "2026-05-10T20:23:00-04:00",
  },
  {
    _id: "msg_017",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "seo",
    body: "Render the 60-second version with the uploaded clip, tennis, beach, stew, lobster, the QR cards, receipts, split summary, and a music track.",
    created_at: "2026-05-10T20:25:00-04:00",
  },
  {
    _id: "msg_018",
    trip_id: BOSTON_CREW_TRIP_ID,
    author: "agent",
    body: "Playable recap created\n1. Format: vertical 9:16\n2. Duration: 60 seconds\n3. Source: uploaded clip, real photos, ticket QR records, receipt images, split summary, chat bubbles, and music\n4. Output: ready to play",
    created_at: "2026-05-10T20:26:00-04:00",
  },
];

const EVENTS: EventDoc[] = [
  {
    _id: "event_hnd_arrival",
    trip_id: BOSTON_CREW_TRIP_ID,
    title: "Arrive at Haneda",
    starts_at: "2026-05-26T10:35:00+09:00",
    ends_at: null,
    location: "Haneda Airport Terminal 3",
    source: "ticket",
    source_id: "ticket_flight_hnd",
    status: "open",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "event_hotel_checkin",
    trip_id: BOSTON_CREW_TRIP_ID,
    title: "Check in near Shibuya",
    starts_at: "2026-05-26T15:00:00+09:00",
    ends_at: null,
    location: "Shibuya Stream Excel Hotel Tokyu",
    source: "ticket",
    source_id: "ticket_hotel_shibuya",
    status: "open",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "event_teamlab_entry",
    trip_id: BOSTON_CREW_TRIP_ID,
    title: "teamLab Borderless entry",
    starts_at: "2026-05-27T11:00:00+09:00",
    ends_at: "2026-05-27T13:00:00+09:00",
    location: "Azabudai Hills",
    source: "ticket",
    source_id: "ticket_teamlab",
    status: "open",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "event_daikanyama_walk",
    trip_id: BOSTON_CREW_TRIP_ID,
    title: "Daikanyama golden-hour walk",
    starts_at: "2026-05-28T17:30:00+09:00",
    ends_at: "2026-05-28T19:00:00+09:00",
    location: "Daikanyama, Tokyo",
    source: "seed",
    source_id: "seed_daikanyama_walk",
    status: "open",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
];

const TICKETS: TicketDoc[] = [
  {
    _id: "ticket_flight_hnd",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "seo",
    type: "flight",
    vendor: "Korean Air",
    amount: 386000,
    currency: "KRW",
    details_json: {
      flight_number: "KE2105",
      from: "GMP",
      to: "HND",
      seat: "12A",
      confirmation: "TOKYO26",
    },
    pdf_url: `${DEMO_ASSET_BASE}/tickets/t_flight_delta_sfo_lax.pdf`,
    qr_data: "M1KIM/SEO TOKYO26 GMPHNDKE2105 026Y012A0001",
    status: "parsed",
    starts_at: "2026-05-26T08:20:00+09:00",
    ends_at: "2026-05-26T10:35:00+09:00",
    latitude: 35.5494,
    longitude: 139.7798,
    origin_latitude: 37.5583,
    origin_longitude: 126.7906,
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "ticket_hotel_shibuya",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "jamie",
    type: "hotel",
    vendor: "Shibuya Stream Excel Hotel Tokyu",
    amount: 592000,
    currency: "KRW",
    details_json: {
      check_in: "2026-05-26T15:00:00+09:00",
      check_out: "2026-05-30T11:00:00+09:00",
      guests: 3,
      room: "Twin + sofa bed",
      confirmation: "SSE-88472193",
    },
    pdf_url: `${DEMO_ASSET_BASE}/tickets/t_hertz_la_rental.pdf`,
    qr_data: "https://hotel.example/booking/SSE-88472193",
    status: "parsed",
    starts_at: "2026-05-26T15:00:00+09:00",
    ends_at: "2026-05-30T11:00:00+09:00",
    latitude: 35.6576,
    longitude: 139.7024,
    origin_latitude: null,
    origin_longitude: null,
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "ticket_teamlab",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "min",
    type: "event",
    vendor: "teamLab Borderless",
    amount: 126000,
    currency: "KRW",
    details_json: {
      date: "2026-05-27",
      time: "11:00",
      tickets: 3,
      confirmation: "TLB-44109",
    },
    pdf_url: `${DEMO_ASSET_BASE}/tickets/t_getty_admission.pdf`,
    qr_data: "https://teamlab.art/eticket/TLB-44109?party=3",
    status: "parsed",
    starts_at: "2026-05-27T11:00:00+09:00",
    ends_at: "2026-05-27T13:00:00+09:00",
    latitude: 35.6602,
    longitude: 139.7407,
    origin_latitude: null,
    origin_longitude: null,
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "ticket_antelope_canyon",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "min",
    type: "event",
    vendor: "Lower Antelope Canyon Tour",
    amount: 132000,
    currency: "KRW",
    details_json: {
      booking_number: "266145927",
      tour: "Lower Antelope Canyon Hiking Tour",
      time: "13:15",
      tickets: 2,
    },
    pdf_url: `${DEMO_ASSET_BASE}/tickets/t_antelope_canyon.pdf`,
    qr_data: "https://fareharbor.com/embeds/book/dixiesantelopecanyon/items/?booking=266145927",
    status: "parsed",
    starts_at: "2026-05-28T13:15:00+09:00",
    ends_at: "2026-05-28T15:15:00+09:00",
    latitude: 36.8619,
    longitude: -111.3743,
    origin_latitude: null,
    origin_longitude: null,
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
];

const EXPENSES: ExpenseDoc[] = [
  {
    _id: "expense_hotel_deposit",
    trip_id: BOSTON_CREW_TRIP_ID,
    payer: "jamie",
    amount: 592000,
    currency: "KRW",
    description: "Shibuya hotel deposit",
    split_among: ["seo", "jamie", "min"],
    source: "receipt",
    receipt_url: `${DEMO_ASSET_BASE}/receipts/e_late_dinner.jpg`,
    status: "parsed",
    created_at: "2026-05-11T00:10:00-04:00",
    updated_at: "2026-05-11T00:10:00-04:00",
  },
  {
    _id: "expense_izakaya_dinner",
    trip_id: BOSTON_CREW_TRIP_ID,
    payer: "seo",
    amount: 138000,
    currency: "KRW",
    description: "Ebisu izakaya dinner",
    split_among: ["seo", "jamie", "min"],
    source: "receipt",
    receipt_url: `${DEMO_ASSET_BASE}/receipts/e_neptune_dinner.jpg`,
    status: "parsed",
    created_at: "2026-05-11T00:12:00-04:00",
    updated_at: "2026-05-11T00:12:00-04:00",
  },
  {
    _id: "expense_suica_topup",
    trip_id: BOSTON_CREW_TRIP_ID,
    payer: "min",
    amount: 45000,
    currency: "KRW",
    description: "Shared Suica top-up",
    split_among: ["seo", "jamie", "min"],
    source: "text",
    receipt_url: null,
    status: "parsed",
    created_at: "2026-05-11T00:14:00-04:00",
    updated_at: "2026-05-11T00:14:00-04:00",
  },
  {
    _id: "expense_punjab_dinner",
    trip_id: BOSTON_CREW_TRIP_ID,
    payer: "min",
    amount: 65000,
    currency: "KRW",
    description: "Shared dinner receipt",
    split_among: ["seo", "jamie", "min"],
    source: "receipt",
    receipt_url: `${DEMO_ASSET_BASE}/receipts/e_punjab_dinner.jpg`,
    status: "parsed",
    created_at: "2026-05-11T00:13:00-04:00",
    updated_at: "2026-05-11T00:13:00-04:00",
  },
];

const PHOTOS: PhotoDoc[] = [
  {
    _id: "photo_hnd_arrival_seo",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "seo",
    url: `${DEMO_ASSET_BASE}/photos/tennis-court.jpg`,
    taken_at: "2026-05-26T10:50:00+09:00",
    latitude: 35.5494,
    longitude: 139.7798,
    width: 1200,
    height: 1600,
    caption: "Tennis court warm-up before the city run",
    place_name: "Morning court",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_shibuya_crossing_jamie",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "jamie",
    url: `${DEMO_ASSET_BASE}/photos/beach-walk.jpg`,
    taken_at: "2026-05-26T18:12:00+09:00",
    latitude: 35.6595,
    longitude: 139.7005,
    width: 1200,
    height: 800,
    caption: "Cold water walk after the drive",
    place_name: "Beach stop",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_teamlab_seo",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "seo",
    url: `${DEMO_ASSET_BASE}/photos/paris-stew.jpg`,
    taken_at: "2026-05-27T11:18:00+09:00",
    latitude: 35.6602,
    longitude: 139.7407,
    width: 1200,
    height: 1600,
    caption: "Stew lunch before the next train",
    place_name: "Azabudai Hills",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_teamlab_jamie",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "jamie",
    url: `${DEMO_ASSET_BASE}/photos/lobster-table.jpg`,
    taken_at: "2026-05-27T11:19:00+09:00",
    latitude: 35.6602,
    longitude: 139.7407,
    width: 1200,
    height: 1600,
    caption: "Seafood table with the trip crew",
    place_name: "Azabudai Hills",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_teamlab_min",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "min",
    url: `${DEMO_ASSET_BASE}/photos/travel-food-03.jpg`,
    taken_at: "2026-05-27T11:20:00+09:00",
    latitude: 35.6602,
    longitude: 139.7407,
    width: 1200,
    height: 1600,
    caption: "Min's food stop angle",
    place_name: "Azabudai Hills",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_daikanyama_cafe",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "seo",
    url: `${DEMO_ASSET_BASE}/photos/travel-vertical-04.jpg`,
    taken_at: "2026-05-28T17:42:00+09:00",
    latitude: 35.6481,
    longitude: 139.7036,
    width: 1200,
    height: 900,
    caption: "Quiet side street before coffee",
    place_name: "Daikanyama",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_nakameguro_river",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "min",
    url: `${DEMO_ASSET_BASE}/photos/travel-vertical-05.jpg`,
    taken_at: "2026-05-28T18:20:00+09:00",
    latitude: 35.6444,
    longitude: 139.6992,
    width: 1200,
    height: 800,
    caption: "Golden hour along the river",
    place_name: "Nakameguro",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_travel_moment_02",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "jamie",
    url: `${DEMO_ASSET_BASE}/photos/travel-moment-02.jpg`,
    taken_at: "2026-05-28T18:25:00+09:00",
    latitude: 35.6444,
    longitude: 139.6992,
    width: 750,
    height: 543,
    caption: "Second angle from the same walk",
    place_name: "Nakameguro",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_travel_moment_03",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "min",
    url: `${DEMO_ASSET_BASE}/photos/travel-moment-03.jpg`,
    taken_at: "2026-05-28T18:27:00+09:00",
    latitude: 35.6444,
    longitude: 139.6992,
    width: 750,
    height: 822,
    caption: "Saved vertical moment for the recap",
    place_name: "Nakameguro",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_travel_moment_04",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "seo",
    url: `${DEMO_ASSET_BASE}/photos/travel-moment-04.jpg`,
    taken_at: "2026-05-28T18:29:00+09:00",
    latitude: 35.6444,
    longitude: 139.6992,
    width: 750,
    height: 876,
    caption: "Another clip-ready still",
    place_name: "Nakameguro",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_travel_moment_05",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "jamie",
    url: `${DEMO_ASSET_BASE}/photos/travel-moment-05.jpg`,
    taken_at: "2026-05-28T18:31:00+09:00",
    latitude: 35.6444,
    longitude: 139.6992,
    width: 750,
    height: 764,
    caption: "Small detail saved for transitions",
    place_name: "Nakameguro",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_travel_moment_06",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "min",
    url: `${DEMO_ASSET_BASE}/photos/travel-moment-06.jpg`,
    taken_at: "2026-05-28T18:33:00+09:00",
    latitude: 35.6444,
    longitude: 139.6992,
    width: 750,
    height: 772,
    caption: "Last still before dinner",
    place_name: "Nakameguro",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_travel_vertical_06",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "seo",
    url: `${DEMO_ASSET_BASE}/photos/travel-vertical-06.jpg`,
    taken_at: "2026-05-29T12:10:00+09:00",
    latitude: 35.6481,
    longitude: 139.7036,
    width: 3024,
    height: 4032,
    caption: "Vertical travel detail",
    place_name: "Daikanyama",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_travel_food_07",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "jamie",
    url: `${DEMO_ASSET_BASE}/photos/travel-food-07.jpg`,
    taken_at: "2026-05-29T13:20:00+09:00",
    latitude: 35.6481,
    longitude: 139.7036,
    width: 4032,
    height: 3024,
    caption: "Lunch table before the next stop",
    place_name: "Daikanyama",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_travel_vertical_08",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "min",
    url: `${DEMO_ASSET_BASE}/photos/travel-vertical-08.jpg`,
    taken_at: "2026-05-29T15:10:00+09:00",
    latitude: 35.6602,
    longitude: 139.7407,
    width: 3024,
    height: 4032,
    caption: "Gallery-like vertical frame",
    place_name: "Azabudai Hills",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_travel_vertical_09",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "seo",
    url: `${DEMO_ASSET_BASE}/photos/travel-vertical-09.jpg`,
    taken_at: "2026-05-29T15:18:00+09:00",
    latitude: 35.6602,
    longitude: 139.7407,
    width: 3024,
    height: 4032,
    caption: "Tall frame for the video close",
    place_name: "Azabudai Hills",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
  {
    _id: "photo_travel_vertical_10",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "jamie",
    url: `${DEMO_ASSET_BASE}/photos/travel-vertical-10.jpg`,
    taken_at: "2026-05-29T19:20:00+09:00",
    latitude: 35.6576,
    longitude: 139.7024,
    width: 3024,
    height: 4032,
    caption: "Final night detail",
    place_name: "Shibuya",
    status: "enriched",
    created_at: ISO_NOW,
    updated_at: ISO_NOW,
  },
];

const MEDIA_ASSETS: MediaAssetDoc[] = [
  {
    _id: "media_uploaded_trip_highlights",
    trip_id: BOSTON_CREW_TRIP_ID,
    member_handle: "seo",
    kind: "video",
    original_name: "uploaded-trip-highlights.mp4",
    mime_type: "video/mp4",
    file_url: `${DEMO_ASSET_BASE}/videos/uploaded-trip-highlights.mp4`,
    file_path: DEMO_VIDEO_PATH,
    duration_seconds: 12,
    trim_start_seconds: 0,
    trim_duration_seconds: 10,
    caption: "Uploaded highlight clip from the group chat",
    status: "ready",
    created_at: "2026-05-10T20:21:00-04:00",
    updated_at: "2026-05-10T20:21:00-04:00",
  },
];

export async function seedBostonCrew(db: Db): Promise<void> {
  await db.collection<TripDoc>(COLLECTIONS.trips).insertOne(TRIP);
  await db.collection<MemberDoc>(COLLECTIONS.members).insertMany(MEMBERS);
  await db.collection<MessageDoc>(COLLECTIONS.messages).insertMany(MESSAGES);
  await db.collection<EventDoc>(COLLECTIONS.events).insertMany(EVENTS);
  await db.collection<TicketDoc>(COLLECTIONS.tickets).insertMany(TICKETS);
  await db.collection<ExpenseDoc>(COLLECTIONS.expenses).insertMany(EXPENSES);
  await db.collection<PhotoDoc>(COLLECTIONS.photos).insertMany(PHOTOS);
  await db.collection<MediaAssetDoc>(COLLECTIONS.mediaAssets).insertMany(MEDIA_ASSETS);
}

export const bostonCrewFixture = {
  trip: TRIP,
  members: MEMBERS,
  messages: MESSAGES,
  events: EVENTS,
  tickets: TICKETS,
  expenses: EXPENSES,
  photos: PHOTOS,
  mediaAssets: MEDIA_ASSETS,
};
